export const AUTOMATION_TEMPLATES = [
  {
    id: 'overdue-notify',
    name: 'Notify on overdue task',
    description: 'Send a notification when a task becomes overdue',
    category: 'notifications',
    trigger_type: 'task_overdue',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: 'Heads up — "{{title}}" is past due' } }],
  },
  {
    id: 'status-to-done-notify',
    name: 'Notify when task completed',
    description: 'Send a notification when a task is marked as completed',
    category: 'notifications',
    trigger_type: 'task_status_change',
    trigger_config: { to_category: 'completed' },
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: '"{{title}}" is done!' } }],
  },
  {
    id: 'assign-notify',
    name: 'Notify on assignment',
    description: 'Notify the assignee when a task is assigned to them',
    category: 'notifications',
    trigger_type: 'task_assigned',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: 'You\'ve been assigned "{{title}}"' } }],
  },
  {
    id: 'delegated-due-soon',
    name: 'Delegated task due soon reminder',
    description: 'Notify when a task you delegated is due within 24 hours',
    category: 'reminders',
    trigger_type: 'delegated_task_due_soon',
    trigger_config: { hours_before: 24 },
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: 'Reminder: "{{title}}" (delegated) is due soon' } }],
  },
  {
    id: 'meeting-logged-create-task',
    name: 'Create follow-up task from meeting',
    description: 'Automatically create a follow-up task when a meeting is logged',
    category: 'tasks',
    trigger_type: 'meeting_created',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'create_task', config: { title: 'Follow up: {{title}}', priority: 'medium' } }],
  },
  {
    id: 'status-change-email',
    name: 'Email on status change',
    description: 'Send an email when a task status changes to a specific value',
    category: 'communications',
    trigger_type: 'task_status_change',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'send_email', config: { subject: 'Status update on "{{title}}"' } }],
  },
  {
    id: 'inactive-task-reminder',
    name: 'Stale task reminder',
    description: 'Notify when a task has had no activity for 7 days',
    category: 'reminders',
    trigger_type: 'task_inactive',
    trigger_config: { days: 7 },
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: '"{{title}}" hasn\'t had activity in 7 days' } }],
  },
  {
    id: 'task-moved-list-notify',
    name: 'Notify on list move',
    description: 'Send a notification when a task is moved to a different list',
    category: 'notifications',
    trigger_type: 'task_moved_list',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: '"{{title}}" was moved to {{list_name}}' } }],
  },
  {
    id: 'comment-notify-assignee',
    name: 'Notify assignee on comment',
    description: 'Notify the task assignee when a new comment is added',
    category: 'notifications',
    trigger_type: 'comment_added',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'send_notification', config: { message: 'New comment on "{{title}}"' } }],
  },
  {
    id: 'webhook-status-change',
    name: 'Webhook on status change',
    description: 'Post to an external webhook when a task status changes',
    category: 'integrations',
    trigger_type: 'task_status_change',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'post_webhook', config: { url: '' } }],
  },
  {
    id: 'date-shift-dependents',
    name: 'Shift dependent dates',
    description: 'Automatically shift dependent task dates when a due date changes',
    category: 'tasks',
    trigger_type: 'date_changed',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'shift_dependent_dates', config: {} }],
  },
  {
    id: 'auto-assign-on-create',
    name: 'Auto-assign new tasks',
    description: 'Automatically assign newly created tasks to a default user',
    category: 'tasks',
    trigger_type: 'task_created',
    trigger_config: {},
    conditions: [],
    actions: [{ type: 'assign_task', config: { user_id: '' } }],
  },
]

export const TEMPLATE_CATEGORIES = {
  notifications: { label: 'Notifications', icon: '🔔', color: '#6366f1' },
  reminders: { label: 'Reminders', icon: '⏰', color: '#0891b2' },
  tasks: { label: 'Task Automation', icon: '⚡', color: '#16a34a' },
  communications: { label: 'Communications', icon: '✉️', color: '#e11d48' },
  integrations: { label: 'Integrations', icon: '🔗', color: '#7c3aed' },
}
