import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.38.5"

// ---------------------------------------------------------------------------
// Role-aware iCal Feed
// ---------------------------------------------------------------------------
// Auth flow:
//   1. Caller supplies ?token= (generated by generate_ical_token RPC).
//   2. Token resolves to a row in calendar_subscriptions which carries user_id,
//      scope, and department_id.
//   3. We look up that user's role from the users table.
//   4. We call get_hidden_categories(org_id, role) to discover which
//      event_type values are suppressed for that role.
//
// Visibility semantics (calendar_category_visibility table):
//   - A row with visible=false hides that category for the given role.
//   - Missing row → fail-CLOSED: category is treated as HIDDEN unless a row
//     with visible=true explicitly allows it OR the org has no visibility rules
//     at all (in which case all events are shown to preserve backward compat).
//   - This differs from the "fail open" behaviour of the alternate version in
//     supabase/edge-functions/calendar-ical-feed.ts, which was intentionally
//     changed here to be conservative (no data leakage on misconfigured orgs).
//
// Existing tokens in calendar_subscriptions remain valid — this function reads
// the same token column and the same table. No migration required.
// ---------------------------------------------------------------------------

serve(async (req) => {
  if (req.method !== "GET") {
    return new Response("Method not allowed", { status: 405 })
  }

  try {
    const url = new URL(req.url)
    const token = url.searchParams.get("token")

    if (!token) {
      return new Response("Missing token", { status: 401 })
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")

    if (!supabaseUrl || !supabaseKey) {
      return new Response("Server configuration error", { status: 500 })
    }

    const supabase = createClient(supabaseUrl, supabaseKey)

    // ── 1. Validate token ────────────────────────────────────────────────────
    // NOTE: reads dept_id, not the legacy department_id — subscriptions
    // created since the dept_id/department_id drift fix (see
    // 20261107000000_fix_calendar_subscriptions_column.sql) only populate
    // dept_id, so reading department_id here silently dropped department
    // scoping and leaked all-org events to department-scoped subscribers.
    const { data: subscription, error: subError } = await supabase
      .from("calendar_subscriptions")
      .select("user_id, scope, dept_id")
      .eq("token", token)
      .single()

    if (subError || !subscription) {
      return new Response("Invalid token", { status: 401 })
    }

    // Update last_accessed_at (non-blocking — ignore result)
    supabase
      .from("calendar_subscriptions")
      .update({ last_accessed_at: new Date().toISOString() })
      .eq("token", token)
      .then(() => {/* fire and forget */})

    // ── 2. Resolve subscriber role ───────────────────────────────────────────
    // Falls back to 'member' when user_id is missing or the row has no role set.
    const subscriberRole = await getSubscriberRole(supabase, subscription.user_id)

    // ── 3. Resolve the org_id for this user ──────────────────────────────────
    // calendar_category_visibility is keyed by org_id. We derive it from the
    // user's department's org. If unresolvable, org_id stays null and all
    // visibility rules are skipped (zero events returned when rules exist).
    const orgId = await getOrgId(supabase, subscription.user_id)

    // ── 4. Get hidden categories for this role ───────────────────────────────
    // Returns a Set of event_type strings that are suppressed.
    // If no visibility rules exist at all for this org, returns an empty Set
    // (all events visible — backward compat with orgs not yet configured).
    const { hiddenCategories, hasAnyRules } = await getHiddenCategories(
      supabase,
      orgId,
      subscriberRole
    )

    // ── 5. Build the events query ────────────────────────────────────────────
    // NOTE: filters out soft-deleted events (deleted_at) — previously missing,
    // which let soft-deleted events keep appearing in exported iCal feeds.
    let baseQuery = supabase
      .from("calendar_events")
      .select(
        "id, title, description, start_date, end_date, all_day, location, zoom_join_url, department_id, event_type, source_id"
      )
      .eq("status", "approved")
      .gte("start_date", new Date().toISOString())
      .is("deleted_at", null)

    // Add org_id as a true predicate for multi-tenant safety.
    // FAIL-OPEN (orgId is null): Preserve backward compatibility for single-tenant setup where
    // ministry_calendar_sources and calendar_events have no org_id column values. This is safe
    // TODAY because Nexus is single-org (one BLW Canada instance). HOWEVER: if architecture
    // changes to multi-tenant (dept-scoped or org-scoped sources), this silent fail-open becomes
    // a CRITICAL LEAK. Future developers: if adding multi-tenant support, change this to fail-CLOSED:
    // require orgId to be set and add .eq('org_id', orgId) unconditionally.
    if (!orgId) {
      console.warn('[calendar-ical] orgId is null for user %s — falling back to unfiltered query. This is safe only in single-tenant mode.', subscription.user_id)
    } else {
      baseQuery = baseQuery.eq("org_id", orgId)
    }

    if (subscription.scope === "department" && subscription.dept_id) {
      // Department scope: own dept events + org-wide events (null department_id)
      baseQuery = baseQuery.or(
        `department_id.eq.${subscription.dept_id},department_id.is.null`
      )
    }

    const { data: allEvents, error: eventsError } = await baseQuery.order(
      "start_date",
      { ascending: true }
    )

    if (eventsError) {
      console.error("calendar_events query error:", eventsError)
      return new Response("Failed to fetch events", { status: 500 })
    }

    // ── 5b. Exclude sources this subscriber has personally hidden ────────────
    // Independent of the org-based category visibility below — user_calendar_
    // source_preferences is per-user, not org-scoped. Events with source_id
    // NULL (manually created, not Google-synced) always pass through.
    const hiddenSourceIds = await getHiddenSourceIds(supabase, subscription.user_id)
    const sourceFiltered = hiddenSourceIds.size
      ? (allEvents || []).filter((e) => !e.source_id || !hiddenSourceIds.has(e.source_id))
      : (allEvents || [])

    // ── 6. Apply role-based category visibility ──────────────────────────────
    // When the org has no visibility rules at all (hasAnyRules=false) we pass
    // everything through — this is backward compatible with orgs that have not
    // yet configured the feature.
    // When rules exist, an event whose event_type is either in hiddenCategories
    // OR whose event_type is NULL (uncategorised) is excluded.
    const events = hasAnyRules
      ? sourceFiltered.filter((e) => {
          const cat = e.event_type ?? ""
          return !hiddenCategories.has(cat)
        })
      : sourceFiltered

    // ── 7. Emit iCalendar ────────────────────────────────────────────────────
    const ical = generateICalendar(events, subscription.scope)

    return new Response(ical, {
      headers: {
        "Content-Type": "text/calendar; charset=utf-8",
        "Content-Disposition": "attachment; filename=calendar.ics",
        "Cache-Control": "public, max-age=300",
      },
    })
  } catch (error) {
    console.error("Calendar iCal error:", error)
    return new Response("Internal server error", { status: 500 })
  }
})

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function getSubscriberRole(supabase: any, userId: string): Promise<string> {
  if (!userId) return "member"
  const { data: user } = await supabase
    .from("users")
    .select("role")
    .eq("id", userId)
    .maybeSingle()
  return user?.role ?? "member"
}

async function getOrgId(supabase: any, userId: string): Promise<string | null> {
  if (!userId) return null
  // Resolve org via users → departments → org_id (if departments table has org_id)
  // Gracefully returns null if the column doesn't exist yet.
  const { data: user } = await supabase
    .from("users")
    .select("department_id, departments(org_id)")
    .eq("id", userId)
    .maybeSingle()
  return user?.departments?.org_id ?? null
}

async function getHiddenSourceIds(supabase: any, userId: string): Promise<Set<string>> {
  if (!userId) return new Set()
  const { data, error } = await supabase
    .from("user_calendar_source_preferences")
    .select("source_id")
    .eq("user_id", userId)
    .eq("hidden", true)

  if (error) {
    console.error("user_calendar_source_preferences query error:", error)
    return new Set()
  }

  return new Set((data || []).map((row: { source_id: string }) => row.source_id))
}

interface HiddenCategoriesResult {
  hiddenCategories: Set<string>
  hasAnyRules: boolean
}

async function getHiddenCategories(
  supabase: any,
  orgId: string | null,
  role: string
): Promise<HiddenCategoriesResult> {
  if (!orgId) {
    // No org context — cannot evaluate rules; return empty set so all events
    // are visible (fail-open for legacy subscriptions with no org).
    return { hiddenCategories: new Set(), hasAnyRules: false }
  }

  // Check whether any rules exist for this org at all.
  const { data: anyRuleCheck } = await supabase
    .from("calendar_category_visibility")
    .select("id")
    .eq("org_id", orgId)
    .limit(1)
    .maybeSingle()

  if (!anyRuleCheck) {
    // Org has no visibility configuration — backward compat, show everything.
    return { hiddenCategories: new Set(), hasAnyRules: false }
  }

  // Org has rules: call the SECURITY DEFINER helper to get hidden categories
  // for this specific role.
  const { data, error } = await supabase.rpc("get_hidden_categories", {
    p_org_id: orgId,
    p_role: role,
  })

  if (error) {
    console.error("get_hidden_categories RPC error:", error)
    // On RPC failure, fail closed: treat all categories as hidden by
    // returning a sentinel value. This prevents accidental data leakage
    // when the rules table exists but is unreadable.
    return { hiddenCategories: new Set(["__ALL__"]), hasAnyRules: true }
  }

  const hidden = new Set<string>(
    (data || []).map((row: { category: string }) => row.category)
  )
  return { hiddenCategories: hidden, hasAnyRules: true }
}

// ---------------------------------------------------------------------------
// iCalendar generation
// ---------------------------------------------------------------------------

function generateICalendar(events: any[], scope: string): string {
  const now = new Date()
  const calendarName =
    scope === "all" ? "Ministry Calendar" : "Department Calendar"

  let ical = `BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//BLW CAN NEXUS//Ministry Calendar//EN\r\nCALSCALE:GREGORIAN\r\nMETHOD:PUBLISH\r\nX-WR-CALNAME:${calendarName}\r\nX-WR-TIMEZONE:UTC\r\nX-WR-CALDESC:${calendarName} from BLW CAN NEXUS\r\nBEGIN:VTIMEZONE\r\nTZID:UTC\r\nBEGIN:STANDARD\r\nDTSTART:19700101T000000Z\r\nTZOFFSETFROM:+0000\r\nTZOFFSETTO:+0000\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\n`

  for (const event of events) {
    const uid = `${event.id}@calendar.blwcannexus.org`
    const startDate = new Date(event.start_date)
    const endDate = event.end_date ? new Date(event.end_date) : startDate

    let dtstart: string
    let dtend: string

    if (event.all_day) {
      dtstart = `DTSTART;VALUE=DATE:${formatDateOnly(startDate)}`
      dtend = `DTEND;VALUE=DATE:${formatDateOnly(endDate)}`
    } else {
      dtstart = `DTSTART:${formatDateTime(startDate)}`
      dtend = `DTEND:${formatDateTime(endDate)}`
    }

    const summary = escapeICalText(event.title)
    const description = event.description
      ? escapeICalText(event.description)
      : ""
    const location = event.location ? escapeICalText(event.location) : ""

    ical += `BEGIN:VEVENT\r\nUID:${uid}\r\nDTSTAMP:${formatDateTime(now)}\r\nCREATED:${formatDateTime(now)}\r\nLAST-MODIFIED:${formatDateTime(now)}\r\n${dtstart}\r\n${dtend}\r\nSUMMARY:${summary}\r\n`

    if (description) ical += `DESCRIPTION:${description}\r\n`
    if (location) ical += `LOCATION:${location}\r\n`
    if (event.zoom_join_url) ical += `URL:${event.zoom_join_url}\r\n`
    if (event.event_type) ical += `CATEGORIES:${escapeICalText(event.event_type)}\r\n`

    ical += `STATUS:CONFIRMED\r\nSEQUENCE:0\r\nEND:VEVENT\r\n`
  }

  ical += `END:VCALENDAR`
  return ical
}

function formatDateTime(date: Date): string {
  const y = date.getUTCFullYear()
  const mo = String(date.getUTCMonth() + 1).padStart(2, "0")
  const d = String(date.getUTCDate()).padStart(2, "0")
  const h = String(date.getUTCHours()).padStart(2, "0")
  const mi = String(date.getUTCMinutes()).padStart(2, "0")
  const s = String(date.getUTCSeconds()).padStart(2, "0")
  return `${y}${mo}${d}T${h}${mi}${s}Z`
}

function formatDateOnly(date: Date): string {
  const y = date.getUTCFullYear()
  const mo = String(date.getUTCMonth() + 1).padStart(2, "0")
  const d = String(date.getUTCDate()).padStart(2, "0")
  return `${y}${mo}${d}`
}

function escapeICalText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/,/g, "\\,")
    .replace(/;/g, "\\;")
    .replace(/\n/g, "\\n")
}
