-- TTS Storage Bucket: holds generated MP3 audio files
-- Bucket is private; access via signed URLs only (generated by generate-tts edge function)
-- Path structure: {cacheKey.slice(0,2)}/{cacheKey.slice(2,4)}/{voiceId}/{cacheKey}.mp3
-- Content-addressable sharding avoids hot-folder issues

-- Insert bucket (idempotent via INSERT IGNORE pattern in Postgres)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'tts-cache',
  'tts-cache',
  false,
  52428800,  -- 50 MB per file
  ARRAY['audio/mpeg']
)
ON CONFLICT (id) DO NOTHING;

-- RLS is already managed by Supabase on storage.objects; no ALTER TABLE needed.

-- Allow authenticated users to read (needed for signed URLs to work)
DROP POLICY IF EXISTS "tts_objects_select" ON storage.objects;
CREATE POLICY "tts_objects_select" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (bucket_id = 'tts-cache');

-- Only service_role can write (via generate-tts edge function)
-- No INSERT/UPDATE/DELETE policies for other roles.
-- This is enforced at the edge function level; RLS just protects the table.
