-- Seed org_chart_nodes / org_chart_edges from the text that was hardcoded
-- in src/pages/OrgChartPage.jsx's NODES/EDGES arrays at the time this table
-- was introduced. Generated, not hand-typed, to avoid transcription errors
-- in organizational text that carries real meaning.

insert into public.org_chart_nodes (id, code, title, sub, flow_caption, details) values
  ('regsec', 'R.SEC', 'Regional Secretary', 'In charge of the region', '', '["In charge of the region. Sets and carries vision from the regional secretary and the man of God, cascading it region → group → department.","Two peer offices report directly: the Pastors'' Office at the group level, and Regional Staff at the regional level.","Regional Staff houses three peer departments — ORS, Regional PFCC and Programs — none of which outranks the Pastors'' Office. Only the Regional Secretary sits above both branches."]'::jsonb),
  ('pastorsOffice', 'PST.OFC', 'Pastors'' Office', 'Group & Subgroup Pastors — Directorate', '', '["Directorate. Sets and carries vision at the group level.","Responsible for group growth qualitatively (individuals maturing) and quantitatively (numbers growing).","Leads Admin, PFCC and Media within the group; directs how regional initiatives cascade down.","Subgroup pastors report to group pastors, who are responsible for their training and raising.","Owns cell-leader accountability as a primary task — PFCC supports this but doesn''t own it.","Head of Foundation School vision within the group."]'::jsonb),
  ('admin', 'ADM', 'Admin', 'Data completeness & accuracy', '', '["Reports to: Pastors (hierarchy) and ORS Data Management (regional oversight)","Operations for the group pastor — organizes information and makes the vision executable. Internal-facing.","Owns data completeness, accuracy and quality in the CMP: names, phone numbers, emails, Kingschat handles.","Tracks meeting attendance and relays absentees to the group pastor for action.","Monitors Foundation School statistics for the group, working with teachers/principals.","Central collaboration point — works with the group pastor, PFCC, Programs and Media.","Confirmed as the intended long-term owner of ongoing data oversight/cleaning — PFCC currently does some of this as a stopgap."]'::jsonb),
  ('pfcc', 'PFCC', 'PFCC', 'Growth — cell system & outreach', '', '["Reports to: Pastors","Growth — brings people from outside into the structure (Admin moves people within it).","Owns the cell system, soul-winning/outreach initiatives, and sales/cell reporting.","Analyzes cell trends: scales high performers, intervenes with underperformers, escalating to coordinator/pastor as needed.","Monitors CMP for cell activity across the group.","Acts as the group pastor''s administrative hands for cell-leader accountability — the pastor remains primarily responsible.","CMP handshake with Admin: jointly validates new data at entry — PFCC confirms the funnel, Admin confirms accuracy.","Coordinates with Regional PFCC on cell trends and outreach initiatives that reach beyond the group."]'::jsonb),
  ('groupMedia', 'MED.G', 'Media', 'Group-level', '', '["Reports to: Pastors","Group-level media — handles the group''s own technical, asset-style and social tasks at group scale.","Keeps tabs on fellowship-level media pages within the group, aiding and supporting them as needed.","Coordinates with Regional Media for regional-scale distribution and standards."]'::jsonb),
  ('cellLeaders', 'CELL', 'Cell Leaders & Coordinators', 'Fellowship level', '', '["Fellowship-level cell leaders and coordinators.","Pastor holds primary accountability; PFCC executes day-to-day tracking and follow-up against monthly plans.","Admin can prompt cell leaders directly when reports are missing, though PFCC owns that relationship primarily."]'::jsonb),
  ('regionalStaff', 'R.STF', 'Regional Staff', 'ORS · Regional PFCC · Programs', '', '["Regional-level umbrella covering the region''s non-group functions.","Houses three peer departments: ORS (Data Management, Finance and Regional Media), Regional PFCC, and Programs.","Carries regional responsibilities, but authority still flows from the Regional Secretary — Regional Staff does not outrank the Pastors'' Office."]'::jsonb),
  ('regionalPfcc', 'R.PFCC', 'Regional PFCC', 'Regional growth & cell oversight', '', '["Reports to: Regional Secretary","Regional-level counterpart to each group''s PFCC — cell and growth oversight at the regional scale.","Sits alongside ORS and Programs as a peer under Regional Staff.","Coordinates with each group''s PFCC on cell trends, escalations and outreach initiatives that reach beyond one group."]'::jsonb),
  ('orsOffice', 'ORS.OFC', 'ORS', 'Office of Regional Secretary', '', '["Regional staff — Office of Regional Secretary.","Houses Data Management, Finance and Regional Media — its three core functions.","Regional Media is Regional ORS Media — the same regional-level media function lives inside ORS, alongside Data Management and Finance.","Sits alongside Regional PFCC and Programs as a peer under Regional Staff — it does not sit above them."]'::jsonb),
  ('regionalMedia', 'MED.OFC', 'Regional Media', 'Technical · Asset · Social', 'Priority order for support — fellowship reaches actual people, group shows identity, the regional page shows all of Canada.', '["Reports to: ORS","Regional-level media department. Technical, Asset and Social sit inside it as sub-departments that generally shouldn''t overlap in responsibility.","Sits inside ORS, alongside Data Management and Finance — not as a separate peer under Regional Staff.","Requests are routed by type: a social media post goes to Social Media; imagery or branded materials go to Asset Media.","Coordinates with each group''s own Media department, which handles group-level distribution and keeps tabs on fellowship media pages."]'::jsonb),
  ('technical', 'MED.T', 'Technical', '', '', '["Reports to: Regional Media","Service presentation tools, technical setup and streaming.","Photography and videography capture."]'::jsonb),
  ('asset', 'MED.A', 'Asset', '', '', '["Reports to: Regional Media","Central repository and organization of all media content — photos, videos, event archives.","Manages video editors and other content producers.","Owns the distribution kit: branded pull-up banners, table covers and standardized flyers for outreach events.","Manages external designers and vendors producing these assets."]'::jsonb),
  ('social', 'MED.S', 'Social', '', '', '["Reports to: Regional Media","Content creation and management for assigned platforms.","Platform owners have full reign — expected to research and actively grow reach and influence, not just post on instruction."]'::jsonb),
  ('dataMgmt', 'ORS.DM', 'Data Mgmt', 'Region-wide data oversight', '', '["Reports to: ORS","Owns region-wide data oversight."]'::jsonb),
  ('finance', 'ORS.FIN', 'Finance', 'Tithes, partnership & accounts', '', '["Reports to: ORS","Manages tithes, partnership and account administration.","Uses administrative means to encourage financial participation region-wide."]'::jsonb),
  ('programs', 'R.PRG', 'Programs', 'Project management', '', '["Reports to: Regional Secretary","Project management for regional, group and fellowship events — an independent peer function under Regional Staff, alongside ORS and Regional PFCC.","Regional programs team manages regional-level programs and any group program the regional secretary is involved in.","Group pastors manage their own group''s programs via the Nexus portal, pulling in Admin, PFCC, coordinators, pastors and cell leaders as needed.","Owns birthday/celebration management and correspondence for senior pastors.","Manages ministry-assigned initiatives — Healing Streams, prayer & fasting, Reach Out World — with advance-warning task tracking.","Owns post-program reporting: before a project is archived, a report captures what worked, what didn''t, and improvement areas, tracked in Nexus."]'::jsonb);

insert into public.org_chart_edges (id, label, details) values
  ('e1', 'Direct Authority', '["Both offices report directly to the Regional Secretary, who is the only office positioned above either branch."]'::jsonb),
  ('e2', 'Direct Authority', '["Both offices report directly to the Regional Secretary, who is the only office positioned above either branch."]'::jsonb),
  ('e3', 'Leads & Directs', '["This is a direct line of authority — the office above leads and directs the office below."]'::jsonb),
  ('e4', 'Leads & Directs', '["This is a direct line of authority — the office above leads and directs the office below."]'::jsonb),
  ('e5', 'Leads & Directs', '["This is a direct line of authority — the office above leads and directs the office below."]'::jsonb),
  ('e6', 'Peer Department', '["Regional PFCC is one of three peer departments under Regional Staff."]'::jsonb),
  ('e7', 'Peer Department', '["ORS is one of three peer departments under Regional Staff — it does not sit above Regional PFCC or Programs."]'::jsonb),
  ('e8', 'Peer Department', '["Programs is one of three peer departments under Regional Staff."]'::jsonb),
  ('e9', 'ORS Function', '["Regional Media is one of ORS''s three core functions, alongside Data Management and Finance."]'::jsonb),
  ('e10', 'ORS Function', '["Data Management is one of ORS''s three core functions, alongside Finance and Regional Media."]'::jsonb),
  ('e11', 'ORS Function', '["Finance is one of ORS''s three core functions, alongside Data Management and Regional Media."]'::jsonb),
  ('e12', 'Media Wing', '["The three media sub-departments generally shouldn''t overlap in responsibility."]'::jsonb),
  ('e13', 'Media Wing', '["The three media sub-departments generally shouldn''t overlap in responsibility."]'::jsonb),
  ('e14', 'Media Wing', '["The three media sub-departments generally shouldn''t overlap in responsibility."]'::jsonb),
  ('e16', 'CMP Data Entry & Check-in', '["At the point of data entry — e.g. a new member''s details from a cell report — PFCC confirms the person came through the funnel correctly and Admin confirms the data itself is accurate. Both sign off before it''s accepted.","The same joint check happens for service check-in verification: Admin validates identity/details, PFCC confirms attendance was captured against the right cell."]'::jsonb),
  ('e17', 'Media Requests Routing', '["Admin and PFCC route group media requests by type: a social media post goes to Social Media, imagery or branded materials go to Asset Media."]'::jsonb),
  ('e18', 'Group ↔ Regional Media Coordination', '["Group Media keeps tabs on fellowship media pages and handles group-level distribution; it coordinates with Regional Media (inside ORS) for regional-scale needs and standards."]'::jsonb),
  ('e19', 'Group ↔ Regional PFCC Coordination', '["Each group''s PFCC coordinates with Regional PFCC on cell trends, escalations, and outreach initiatives that extend beyond one group."]'::jsonb),
  ('e20', 'Reports Up — Data Visibility', '["Admin reports up to the ORS Data Management Manager so the region has visibility into group activity — this is a reporting line, not a line of authority."]'::jsonb),
  ('e21', 'Executes Accountability', '["PFCC acts as the group pastor''s administrative hands, keeping cell leaders on track against monthly plans."]'::jsonb),
  ('e22', 'Primary Ownership', '["Cell-leader accountability is a primary task for the group pastor — formal and informal one-on-ones with coordinators and leaders. PFCC supports this but doesn''t own it."]'::jsonb),
  ('e23', 'Programs ↔ Media Coordination', '["Programs and Media collaborate on event execution and media coverage."]'::jsonb);
